### ISSUE TITLE
[UX Bug] Switching board visibility (public/private) causes new list text field to not work

### ISSUE THREAD

**Issue by neandrake** [libreboard/libreboard#104]
### Test
1. Create or open a board
2. Ensure a new list form is on the page and that its text field ('Add a list...') has focus to type in the name. Verify field accepts keyboard input.
3. Click to switch board from public to private (or vice-versa).
4. Click to focus the new list text field.

### Result
After switching the visibility setting, the 'Add a list..' field will no longer accept keyboard input.

### Notes
1. There is a small clickable empty space next to the Save button causes the input field to hide. Clicking again to add a list will cause the input field to take keyboard input again.
2. This issue occurs as well when clicking the Star icon.
3. If the text field does not have focus before changing visibility, this issue will not occur. The text field must be on the visible page for this to be a problem.
4. This issue also occurs when clicking the board name in top left to rename the board.
5. System: OS X 10.10 / Firefox 35

**Comment by neandrake** [comment]
For Note 1, I think the small clickable space next to the Save button is supposed to be an X similar to other forms, but there is no X icon. It behaves like other X buttons on other forms however.

**Comment by mquandalle** [comment]
The close [X] icon is fixed.

**Comment by mquandalle** [comment]
Fixed in the `master` branch. The fix will be in the next release (v0.9).
