### ISSUE TITLE
Missing Functionality

### ISSUE THREAD

**Issue by neandrake** [libreboard/libreboard#106]
I apologize if this Issue is unnecessary, but I thought I would make a list of functionality that appears to either not work or is missing. I could not find this documented elsewhere; perhaps these should be split into separate issues?

- List Actions Menu
  - Add a card... (this functionality exists already, but this menu item does nothing)
  - Subscribe (nothing appears to happen, no manner of listing subscribed lists)
- Sidebar
  - Menu
    - Archived Items (nothing appears to happen)
    - Close Board... (the board can be closed, but the warning refers to the 'Boards' menu in top left having some option to view and re-open closed boards. This does not appear to exist.)
- Settings
  - None of the settings links ("Change ...") appear to have an effect.
- Profile
  - Clicking avatar - would expect ability to select avatar, nothing happens

System: OS X 10.10 / Firefox 35

**Comment by superg2** [comment]
+1 for all those items :)

**Comment by davideuler** [comment]
+1 for Archived Items (nothing appears to happen)
