### ISSUE TITLE
Ability to change username

### ISSUE THREAD

**Issue by singpolyma** [libreboard/libreboard#112]
Right now I am stuck with the long name libreboard inferred from my full name, instead of a more useful handle.

**Comment by fnky** [comment]
I'd imagine that you have both a username, used to **@mention** people and the full name for personal identity.

**Comment by singpolyma** [comment]
@fnky Yes, but right now one cannot choose the username, it's just created when your account is created out of your full name.

**Comment by rnaby** [comment]
I just installed libreboard... But I wants a default username and password. What is the default username and password?

**Comment by mquandalle** [comment]
Implemented in `master`, and testable in http://newui.libreboard.com.
