### ISSUE TITLE
Too much information or not?

### ISSUE THREAD

**Issue by BatuhanK** [libreboard/libreboard#115]
Hi,
I just noticed that when you search people from sidebar, meteor.js responding with too much data.

I can't use this information because the data that leaks is encrypted. But I guess 'probably' there is no active filter for this search and ( hypothetically ) if someone add 3rd party logins ( like Twitter,Github etc.) it'll include the user's tokens too.

Can you guys check this out, is it the expected behavior ? 

![](http://i.imgur.com/JQCnmQa.png)

**Comment by mquandalle** [comment]
It seems to be a bug with the easy-search feature (https://github.com/matteodem/meteor-easy-search/issues/126), I have disabled this functionality while this get resolved. Thank you for the bug report.

cc @yasaricli who implemented this feature.

**Comment by BatuhanK** [comment]
Thanks, I hope you guys figure it out easily :)

**Comment by mquandalle** [comment]
I fixed the bug and re-enabled the search feature in http://git.libreboard.com/libreboard/libreboard/commit/b7daaafec6a81b7e512991e757b6438b32ed6187

Thank you very much for this security report.
