### ISSUE TITLE
Want a mobile application ?

### ISSUE THREAD

**Issue by florent37** [libreboard/libreboard#122]
Hello, I am a mobile developper (Android/iOS) and I want to contribute to open-source projects.
Are-you interested by making a mobile application for libreboard ?

**Comment by mquandalle** [comment]
The idea was more to wrap the application in Cordova. Could you share the name of some applications you created?

**Comment by florent37** [comment]
You can find all my application on my linkedin profile : https://www.linkedin.com/profile/view?id=297860624

**Comment by ocdtrekkie** [comment]
@florent37 "You and this LinkedIn user don’t know anyone in common

You can only view the profiles of users within your network. However, as you add connections, you may discover people you know in common."

**Comment by ocdtrekkie** [comment]
As a personal note from a Sandstorm user, I really like how Tiny Tiny RSS has a proper mobile-style app and connects to my Tiny Tiny RSS instance in Sandstorm via an API key. I would definitely find it a key perk of any app that can do that.

**Comment by florent37** [comment]
It's true, i'm sorry...

You can check some of application i'm working on at : 
http://whaterz.com/
http://whaterz.com/apk/ociney.apk
http://whaterz.com/apk/whatwhat.apk

(it's just some proof of contents, not on the google play store)

And I'm currently work on https://play.google.com/store/apps/details?id=fr.francetv.apps.info

**Comment by AbeEstrada** [comment]
Maybe if Libreboard has a public API there's no need for an official mobile app.
Twitter gained a lot of traction because the API (right now is in another direction) but I think that can help.

**Comment by florent37** [comment]
Yes ! If you made a public API the developers will be able to develop open-source mobile solutions for libreboard

**Comment by mquandalle** [comment]
We already have a *de facto* public API. Meteor enforce you to separate the source code of your application (written in javascript and served over HTTP) and the data (using the DDP protocol). The DDP protocol has a publish/subscribe feature and a RPC model that are better than a REST API to develop a mobile application. So the easier way for a native mobile application to communicate to a LibreBoard server would be to use a DDP client.

Of course, this API is not stabilized and not document at all. In fact I even have some significant change ideas in mind. But when it gets more mature no doubt that this will used as a public API.

**Comment by Telemakhos** [comment]
I've just read this... I opened an issue regarding the development of an API (https://github.com/libreboard/libreboard/issues/128). I guess the mobile clients should work with DDP in order to maintain the real-time features, but for integration with 3rd party services IMO REST would be the way to go.

**Comment by mquandalle** [comment]
Yes that's the plan — DDP for mobile apps, REST for third party integration.

**Comment by daithi-coombes** [comment]
Sorry for commenting on closed issue but has anybody got any `ddp clients` working or any recommendations?  

Hope to test this one...
https://github.com/kenyee/android-ddp-client

**Comment by wingZero21** [comment]
Would be good if there was a mobile application or if there was mobile web support for it.

**Comment by m0nhawk** [comment]
Any update on the mobile version? It would be great to have native mobile experience, at least web.

**Comment by xet7** [comment]
@m0nhawk 

This issue is already closed, please continuet at open issues, that are:
- Switch to React #299 
- Creating React native mobile apps #480

Somebody at Wekan chat channel said about looking at switching to React. More developers and pull requests welcome.
