### ISSUE TITLE
Improve Performance

### ISSUE THREAD

**Issue by neandrake** [libreboard/libreboard#125]
Time to load a page for libreboard seems to be awfully slow for how little content ends up being displayed. There are also some visual indications of a theme being loaded, then the board switches color. It would be nice if someone could profile the board and see where time is being spent loading boards and other pages.

**Comment by diego-vieira** [comment]
Can't see to reproduct with the latest version as of today.

**Comment by mquandalle** [comment]
The lastest work on the `master` solves a lot of performance issues. They will be released in v0.9.
