### ISSUE TITLE
use fa-star instead of fa-star-o if the board is starred

### ISSUE THREAD

**Issue by fnkr** [libreboard/libreboard#137]
**Current**
![image](https://cloud.githubusercontent.com/assets/616991/6174636/43e96b88-b2f0-11e4-80e6-5ab197cf81d0.png)![image](https://cloud.githubusercontent.com/assets/616991/6174675/8b180c9e-b2f0-11e4-9ea7-87943f3d68ba.png)

**Suggestion**
Replace [fa-star-o](https://fortawesome.github.io/Font-Awesome/icon/star-o/) with [fa-star](https://fortawesome.github.io/Font-Awesome/icon/star/) if the board is starred and remove the background shadow.
![image](https://cloud.githubusercontent.com/assets/616991/6174636/43e96b88-b2f0-11e4-80e6-5ab197cf81d0.png)![image](https://cloud.githubusercontent.com/assets/616991/6174643/4e59fe98-b2f0-11e4-859e-95a483dc083b.png)

**Benefits**
- more obvious
- you can see if the board is starred or not even if the icon is hovered

**Comment by mquandalle** [comment]
This is done on the newui branch that you can see on http://git.libreboard.com/libreboard/libreboard

**Comment by fnkr** [comment]
Awesome, thanks!
