### ISSUE TITLE
Just wondering the status of the project

### ISSUE THREAD

**Issue by nata-goddanti** [libreboard/libreboard#145]
Its been really quiet in here the last few weeks.....

**Comment by CNek** [comment]
Same thoughts here.
Stumbled upon this project after a deep research, seems to be promising !

**Comment by ichpuchtli** [comment]
Hey guys, check out the active discussions going on over in issue https://github.com/libreboard/libreboard/issues/94

**Comment by 0xF3F** [comment]
http://git.libreboard.com/libreboard/libreboard/commits/master

**Comment by fnkr** [comment]
@0xF3F Network view is better, you can see all branches at once:
http://git.libreboard.com/libreboard/libreboard/network/master

**Comment by theSoenke** [comment]
Whats is the current ETA for the newui and being back on github? End of february it was less than a month https://github.com/libreboard/libreboard/issues/94#issuecomment-720780

**Comment by mquandalle** [comment]
I didn't write a lot of lines of code the last few weeks — or at least, not as much as I wanted. But I have been thinking about this project a lot. I'm considering building a company to develop the project full time, inspired by gitlab for instance. I've been thinking about a strategy, talking with a few platforms that could integrate LibreBoard in their ecosystem, and a lot of various things.

The short-term goal is still to finish the new ui, and get back to business on github.

**Comment by Shekar73** [comment]
@mquandalle is there any ETA when the new UI will be back on github so that it can get contributions from the open source to leverage the existing active interest(>3500 stars!!)? I am assuming it is going to follow the model of open source for community contributions and paid model for some extra 'enterprisey' features, like gitlab? Is that a fair assumption?

**Comment by Matthias84** [comment]
Would love to see the project back and for selfhosting. Raising some money to do the job is fairly ok (e.g. fundraising drive). Hope it's not going to become just another commercial simplified project management solution ... :-/

**Comment by Shekar73** [comment]
I agree. This project has lot of potential. I only hope it does not end up in the open source deadpool due to the long delay!

**Comment by andreioprisan** [comment]
any update in the last few weeks? the newui URL still shows the initial version

**Comment by fnkr** [comment]
There were updates [on the newui-2 branch](http://git.libreboard.com/libreboard/libreboard/commits/newui-2).

I have a running instance here: https://libreboard-newui.fnkr.net

**Comment by mquandalle** [comment]
The code is back on github. I have done some significant re-write of the internals, fixing quite a few bugs and performances issues. The UI is not “finished”, there are a lot of glitches and some missing features (eg, card attachments), but I'll continue to develop it here on GitHub.

**Comment by ocdtrekkie** [comment]
Back on Github! \o/

**Comment by natagoddanti** [comment]
:+1:  :+1:  :+1:
