### ISSUE TITLE
Card detail modal load performance

### ISSUE THREAD

**Issue by helixzor32** [libreboard/libreboard#154]
I have noticed on the version of Libreboard we have installed (pulled a copy awhile back) now has a large performance issue now that we have many boards / lists / cards set up.

I have a dev server set up with no cards/boards and what not - started a few cards. Loading the detail window is instantaneous. However - on our production one - loading a card can take up to 5 seconds before the window pops up. Also - closing it has the same effect. 

Is anyone aware of a previous bug that was submitted or of it's a modal issue that is causing this? Given that it is a MongoDB and even with how many boards/cards/lists - which isn't really a whole lot - doesn't seem that this would be a database issue..

Any ideas?

**Comment by fix** [comment]
first idea coming to mind, the subscription is pulling a lot of data to the browser and you have javascript performance issue.

**Comment by fix** [comment]
my comment is related to this http://git.libreboard.com/libreboard/libreboard/blob/master/server/publications/boards.js#L47

**Comment by helixzor32** [comment]
Are you saying that the subscription issue would be fixed in that revision? I am checking my code and I have that exact implementation - alongside your comment :)

**Comment by fix** [comment]
no, it is not fixed the comment just mention some potential performance issue. do you have lot's of activities and comments in your slow boards?

**Comment by helixzor32** [comment]
Activities and cards yes - but not comments. At the moment - we are not utilizing comments on cards.

**Comment by helixzor32** [comment]
Fixed - it was the activities pull on that same script. We have been using for awhile and that activities find pulled all historical activities - which only grew as time passed by. I have changed to only pull the last 50 and now we're back in business. Thanks!

**Comment by mquandalle** [comment]
Let's keep this issue open until we have a proper fix (infinite scrolling/subscription paging).

**Comment by fix** [comment]
I agree, it is not a proper fix. Happy i could help.

**Comment by mquandalle** [comment]
I separated the activities subscription from the main board subscription, and implemented an infinite scrolling system to download the activities page per page (20 activities per page). The commit is visible [here](http://git.libreboard.com/libreboard/libreboard/commit/9ed1a6038616789c6febc107956e37f45b698ab5) and will be in the next release.

**Comment by fix** [comment]
Well done!
