### ISSUE TITLE
'Add a card' is not working after the card is dragged and dropped in a different list

### ISSUE THREAD

**Issue by nata-goddanti** [libreboard/libreboard#158]
When you drag and drop a card on a different list or when you move the lists around, the 'add a card'  button is not working on BOTH the lists. It appears to be an issue  only on starred boards!!

**Comment by mquandalle** [comment]
I can't reproduce this bug with the current master version (or on http://newui.libreboard.com).

**Comment by yasaricli** [comment]
:+1:

**Comment by mko-x** [comment]
Cannot reproduce as well with latest master
