### ISSUE TITLE
Data seems to be leaking from from one user to the other user

### ISSUE THREAD

**Issue by nata-goddanti** [libreboard/libreboard#161]
The boards created logged in as one user are getting displayed when I log out and log in as a different user. 

Below is the screenshot of the boards I created logged in as 'test1test1'

![image](https://cloud.githubusercontent.com/assets/203255/7636953/59709294-fa1f-11e4-9d17-50842fa4ae30.png)

Now when I log in as 'test2test2' the same boards created as previous user are getting displayed

![image](https://cloud.githubusercontent.com/assets/203255/7636994/a049053e-fa1f-11e4-96b5-592e19e0b5ca.png)

**Comment by mquandalle** [comment]
The above commit fixes the issue but v0.9 still need some work before I can release a updated spk.

**Comment by mquandalle** [comment]
I just realized that I forgot to say thank you for the bug report @nata-goddanti :)

**Comment by nata-goddanti** [comment]
Sure!! happy to do it..Thanks for the awesome work. I, for one  learning a lot from your work :-)

**Comment by nata-goddanti** [comment]
btw...this open issue might be related to this... https://github.com/libreboard/libreboard/issues/218
