### ISSUE TITLE
Downloaded Meteor Version looks different from your board.

### ISSUE THREAD

**Issue by rwatts3** [libreboard/libreboard#169]
I have installed and setup with meteor and noticed that it looks significantly different from the official libreboard's board. 

Are there extra packages I must install to get the same look and feel ?

**Comment by ePirat** [comment]
That is because the old Version was infringing Trello's copyright, so a UI redesign was done/is currently worked on. The online libreboard is still an older version than the current master.

**Comment by mquandalle** [comment]
Thanks @ePirat :)
