### ISSUE TITLE
What is the status on the next edition?

### ISSUE THREAD

**Issue by rwatts3** [libreboard/libreboard#171]
Hello what is the current status for 0.9.0 ?

**Comment by mquandalle** [comment]
v0.9 is a work in progress. The version requires major re-factoring of the internals (about 70% of the code is re-written). You can follow the developement here on GitHub, see the open issues with [the milestone filter](https://github.com/libreboard/libreboard/milestones), or test it live on http://newui.libreboard.com.

I'm working on it every day, and making significant progress. There will be at least two or three release candidates before the final v0.9.

**Comment by yasaricli** [comment]
:+1:
