### ISSUE TITLE
Bower dependency list must be a dictionary...

### ISSUE THREAD

**Issue by lscordilis** [libreboard/libreboard#172]
![image](https://cloud.githubusercontent.com/assets/12753650/8010671/18f366ac-0b80-11e5-96c1-dfb5e075ab70.png)

So I'm attempting to build the application in Ubuntu 14.04. I've got all the right dependencies as far as I can tell. However, I'm getting this error, I'm not quite sure what it means.

The contents of my bower.json are:
![image](https://cloud.githubusercontent.com/assets/12753650/8010738/bcfeb0f8-0b80-11e5-839c-a867708a00c4.png)

and those of my bower_components/perfect-scrollbar/bower.json are:
![image](https://cloud.githubusercontent.com/assets/12753650/8010752/da6db594-0b80-11e5-930f-c9cbfb0fcad2.png)

Thanks for your time

**Comment by mquandalle** [comment]
This seems to be a problem with https://github.com/mquandalle/meteor-bower, but I'm not sure what is causing it. Maybe you have any additional indication to help me reproduce it?

**Comment by ePirat** [comment]
I had the same problem when I tried to build the app, after I deleted the build directory (which already had an older version) it worked fine. Not really sure why.
To which directory are you trying to build? Or are you trying to run it using `meteor run`?

**Comment by lscordilis** [comment]
I've deleted and re-built the directory with git clone directly from this repo. I get the same problem every time when I cd into the libreboard directory and run meteor

**Comment by ePirat** [comment]
Can you show me the full command you are trying to run please?

**Comment by mquandalle** [comment]
`meteor` ;)

**Comment by ePirat** [comment]
It sounds like you have built the app inside the source directory, as per [this](http://stackoverflow.com/questions/26524346/meteor-fails-to-run-after-building-a-meteor-app) Stackoverflow answer:

> Meteor picks up all javascript files in your project's folder including nested folders. By saving your bundle in the same directory as your project, you just duplicated a lot of files and now Meteor is going to pick them up as "new source files". To avoid this, output your bundles to a separate directory from your project or to a hidden folder that is ignored by Meteor build tool (any folder name starting with a dot).

(I've just tried out and built the app to a folder inside the app sources, to confirm that this causes the issue, and have exactly the same errors as you have. Note that the built tool will even warn about this.)

If you are still experiencing problems, even choosing a build directory outside the meteor app sources, I can write a short guide how to get it up and running.

**Comment by mquandalle** [comment]
BTW, I guess there isn't anything specific to LibreBoard with this bug, but it is instead a problem with https://github.com/mquandalle/meteor-bower.

**Comment by ePirat** [comment]
@mquandalle I don't think it has anything to do specifically with it, it's just that meteor will try to build files that are already built, resulting in a lot of errors.

**Comment by mquandalle** [comment]
So we are talking about `meteor build` here, right?

**Comment by lscordilis** [comment]
Whatever the problem was, it's not happening now. My guess is something was wrong with the bower package manager or it wasn't installed properly, because I updated all my packages, rebuilt libreboard/ again and was able to run it. I really appreciate your help, guys. Been trying to get this working on a private server for a few days now.

**Comment by ePirat** [comment]
Note that, for production use you should use the package created with `meteor build` not just run `meteor`

**Comment by lscordilis** [comment]
Okay, thanks for the advice. I'm pretty new to meteor, but so far I'm really liking it

**Comment by mquandalle** [comment]
I'm sorry you had an hard time installing Libreboard. Note that you are dealing with in flux software, once v0.9 is released, docker images will be a reasonably easy way to install Libreboard on your own server.

**Comment by lscordilis** [comment]
Of course, I understand. You guys have done an awesome job so far, and I'm looking forward to contributing in the near future, once I get my feet wet
