### ISSUE TITLE
Export/Backup while updating

### ISSUE THREAD

**Issue by ajjaic** [libreboard/libreboard#174]
Is there a way to export data from an existing libreboard instance and then import that data into an updated libreboard instance?

How do you currently update your libreboard instance to a newer version,  while migrating the data from the older instance of libreboard? Or is it not currently possible to do this?

**Comment by mquandalle** [comment]
LibreBoard puts its whole state and users data in the linked MongoDB (doesn't write the file system, or do anything else). So to backup your entire state you have to `mongodump` this database.

To upgrade to a new version, you'll have to stop the old version and start the new one. The new version will detect that some data have an old format and will automatically migrate them on start.

**Comment by ajjaic** [comment]
So the update automatically happens when the old version is replaced with the new version and is restarted. Thanks for the information.
