### ISSUE TITLE
Latest commits broke boards in Safari completely.

### ISSUE THREAD

**Issue by ePirat** [libreboard/libreboard#176]
The latest commits, I suspect namely 92dd05d broke the board on Safari.
![bildschirmfoto 2015-06-09 um 16 03 28](https://cloud.githubusercontent.com/assets/323210/8059677/a00a5490-0ec1-11e5-8827-5428a2bcdc4c.png)

When I am trying to click on any of the buttons in the card detail panel, the whole board flickers like crazy and the pointer changes from link to normal rapidly, like if normal content and a link would be overlapping and interfering.

**Comment by ePirat** [comment]
This affect drag-and-drop of Labels as well, I am not able to drag label to cards from the sidebar anymore.

**Comment by mquandalle** [comment]
I tried on Safari v8.0.8 and wasn’t able to reproduce this bug. But since the line you pointed contained a mistake (`document` instead of `document.body`) I corrected it in the above commit. Does that solve this issue?

**Comment by ePirat** [comment]
Indeed, it is fixed now.

**Comment by mquandalle** [comment]
Cool! Thank you for the precise report!
