### ISSUE TITLE
newui editing or creating a label always causes its colour to be set to green

### ISSUE THREAD

**Issue by singpolyma** [libreboard/libreboard#189]

**Comment by singpolyma** [comment]
It appears that `var selectLabel = Blaze.getData(selectLabelDom);` always returns colour of "green" and name of "", but name works because it is being selected out of the DOM directly.

**Comment by singpolyma** [comment]
Manually calling `Boards.update("board-id", { "$set": { "labels.2.color": "orange" }  });` worked, so it's just that the wrong data is being selected.

**Comment by singpolyma** [comment]
The line in question: https://github.com/libreboard/libreboard/blob/46cc69153482a6138e1057ece9cec836dd95451e/client/components/cards/events.js#L170

**Comment by ePirat** [comment]
That's weird, which browser are you using? I can't reproduce with Safari or latest Chrome.

**Comment by singpolyma** [comment]
I can no longer reproduce this.
