### ISSUE TITLE
Use GitHub releases for the builds

### ISSUE THREAD

**Issue by ePirat** [libreboard/libreboard#194]
Whenever a new version is released, it should be tagged and a build tarball attached, which was made with meteor build, is order to not require everyone interested in a manual installation to download meteor.

**Comment by ocdtrekkie** [comment]
It... will be. 0.9 isn't done, and 0.8 cannot be posted.

**Comment by ePirat** [comment]
Ok great, when 0.9 is released together with the build tarball I will update the wiki installation instructions.
