### ISSUE TITLE
Lower minimum username length to 3

### ISSUE THREAD

**Issue by ePirat** [libreboard/libreboard#202]
It would be great if this could either be configured or just generally lowered, as I have users with short nicknames that can't register due to the username length restriction.

**Comment by mquandalle** [comment]
The minimum length is defined [here](https://github.com/libreboard/libreboard/blob/f039923ac134e4a3cc70a1a7d47c21460676b1c0/client/config/accounts.js#L8). I don't have a strong opinion on whether or not it should be lowered.

**Comment by ocdtrekkie** [comment]
I can't see a huge reason to have a minimum account name length on a privately-owned board. And if you're a company with employees with two-character last names like "Li", it might not hurt to support first initial/last name schemes there, which would be three characters.
