### ISSUE TITLE
change color of board not work

### ISSUE THREAD

**Issue by leo-combes** [libreboard/libreboard#205]
If you try change color of board, its always remains in green.

**Comment by leo-combes** [comment]
I think is a permissions problem. I not know how, but I create a board and now I can't modify the public/private status, color, etc.

**Comment by mquandalle** [comment]
It should be fixed in 8cf9ec266055f065c428216d53018c83b63675c6

**Comment by leo-combes** [comment]
I have another problem related with permissions, as I said before, I create a board and today cant edit or add users. How can edit permissions? They are at mongo DB? If yes, which file have the DB or how can edit this?
