### ISSUE TITLE
Login with LDAP

### ISSUE THREAD

**Issue by snolahc** [libreboard/libreboard#212]
Hi,

it would be awesome to be able to integrate Libreboard in my company. However, we (as 80% of companies) rely on LDAP auth for our users, and integrating Libreboard without this auth method won't be possible.

I saw some discussions on Meteor to integrate MS ActiveDirectory auth, so LDAP should be fully supported.

Sandstorm doesn't support LDAP auth either and it's still the reason why we can't have it to work with our team.

Thanks :)

**Comment by ocdtrekkie** [comment]
This is a duplicate issue though. Also: @kentonv

**Comment by kentonv** [comment]
FWIW, Sandstorm plans to add LDAP support, possibly quite soon.

**Comment by snolahc** [comment]
Closing this issue, merging in #119 , thanks @ocdtrekkie
