### ISSUE TITLE
Meta Boards

### ISSUE THREAD

**Issue by snolahc** [libreboard/libreboard#213]
Hi,

Libreboard is the best tool to create lists.
In order to organize lists, we need to make lists of lists with priorities.
This tool allows us to be totally free on our organization, but could suggest a way to easily have a "todo list" from several boards where cards are assigned to me.

Managing those "duplicated/meta cards" would affect the underlying boards, cleaning them of the "done" stuff. This would be another board collecting cards with specific attributes/tags/...

What do you think of it ?

**Comment by mquandalle** [comment]
Did you close this on purpose?
