### ISSUE TITLE
Some board menu items don't work

### ISSUE THREAD

**Issue by bluepuma77** [libreboard/libreboard#215]
Git cloned the latest master, some board menu items don't work, nothing happens when clicked.

"Permissions"
"Copy this board"
"Close Board..."

The browser console tells me no errors.

I am logged in, everything else works, like creating new boards, lists and cards.

![libreboard-permissions](https://cloud.githubusercontent.com/assets/5221187/8376272/74236668-1c05-11e5-8bc3-c24bfc99a52c.png)

**Comment by kayrules** [comment]
+1

**Comment by kadishmal** [comment]
:+1: I have the same issue when clicking on the "Permissions" menu item.

**Comment by yuecen** [comment]
+1

**Comment by jamessanders** [comment]
:+1:
