### ISSUE TITLE
Building on windows

### ISSUE THREAD

**Issue by sonicviz** [libreboard/libreboard#222]
Hi,
Getting up to speed on Meteor I thought I'd give it a shot running libreboard locally.

I have Node, Mongo installed and completed the "official" Meteor tutorial aok.

I cloned the repo but there's a couple of issues that seem to break.
Following install instructions: meteor build .build --directory
it looks like it installs a few packages then throws a cryptic error:
D:\C#\libreboard>meteor build .build --directory

C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
SyntaxError: Unexpected token

Any clues?

ty!

**Comment by ePirat** [comment]
I have no idea why that happens. Please post the full steps you've done here so we can better reproduce what the problem could be.

**Comment by sonicviz** [comment]
The steps are exactly what I outlined above.

**Comment by ePirat** [comment]
I need every command you performed and it's output. Your description above sounds fine, that's why I am asking for this.

**Comment by sonicviz** [comment]
Input
D:\C#\libreboard>meteor build .build --directory

Output
C:\Users\Paul\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
throw(ex);
^
SyntaxError: Unexpected token

**Comment by ePirat** [comment]
I mean more like the steps that you did before that, as it seems there is something wrong with your meteor install.

**Comment by ePirat** [comment]
At least I am currently not able to find any known bug on [node-fibers](https://github.com/laverdet/node-fibers/issues) repo which could explain that.

**Comment by sonicviz** [comment]
afaik there's nothing wrong with my meteor install. I'm on windows.
It's been running just fine with other projects. 

Maybe there's some windows specific setup needed that's missing from your docs?

**Comment by sonicviz** [comment]
I just found it thanks to help from laverdet at laverdet/node-fibers#235

Issue was corrupted os.json file in softwarerero_accounts-t9n meteor base package so I resolved it by deleting it and on new build it re-downloaded a new one that was ok.

Still unsure why it was corrupt or why the problem only occurs on with github repos I cloned.

**Comment by xet7** [comment]
@sonicviz @ePirat 

@entrptaher today added new Windows instructions, you can try does it work for you:
https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows

**Comment by ePirat** [comment]
I am not using Windows, so I can't try the guide.

**Comment by entrptaher** [comment]
The fibers related issues are all over the github. Building on windows is the problem we are facing right now. Let's see how can we solve this problem.

![](https://i.imgur.com/2RLNhh5.png)
