### ISSUE TITLE
Newui board breaks in Internet Explorer

### ISSUE THREAD

**Issue by kayrules** [libreboard/libreboard#225]
I'm using IE 11. 
Board displayed as per image below:

![image](https://cloud.githubusercontent.com/assets/461079/8792969/13b320f6-2fa2-11e5-9827-09d0d28acbc2.png)

**Comment by kayrules** [comment]
I fixed the issue by assigning a style `.min-height` equal to the content height for `<div id="content">` under `meteor startup` and `Template.defaultLayout.rendered` functions. 

This is my dirty way to fix the issue. Kindly share if you have better way of doing it.

```
var AdjustForIE = function(){
	if (DetectIE()) { //-- call another function to detect IE
		var viewPortHeight = $(window).height();
		var headerHeight = parseInt($('#header').css('height'));
		var contentHeight = parseInt(viewPortHeight-headerHeight); 
		$('#content').css('min-height', contentHeight);
	}
}

Template.defaultLayout.rendered = function() {
    if(!this._rendered) {
     	this._rendered = true;
		AdjustForIE();
    }
}

Meteor.startup(function(){
	$(window).resize(function(){
		AdjustForIE();
	});
});
```

**Comment by mquandalle** [comment]
Re-opening until this is fixed in `master`.

**Comment by mquandalle** [comment]
Thanks for the report! It's amazing that you’ve come up with the solution in the above snippet, you should have to be very motivated! Hope this will be better now :)

And don’t hesitate to report any other IE problem, as a linux user I tend to forget this browser...
