### ISSUE TITLE
How to configure smtp for own server installation?

### ISSUE THREAD

**Issue by kayrules** [libreboard/libreboard#228]
How to configure smtp for own server installation under libreboard?
I have setup my environment according to guide in issue #187 as below:
```
export MONGO_URL='mongodb://127.0.0.1:27017/libreboard'
export ROOT_URL='https://example.com'
export MAIL_URL='smtp://user:pass@mailserver.example.com:25/'
export PORT=8080
```
Tested my smtp connectivity using telnet command working just fine.
But no email send out on any activities from libreboard.

pls help. thanks.

**Comment by kayrules** [comment]
I managed to solved this issue. Not sure if this is the best way of doing it btw.
I just created a file called `smtp-config.js` under /server folder and put codes below:

```
Meteor.startup(function () {
	smtp = {
		username: 'yourUsername', 
		password: 'yourPassword',
		server:   'smtp.domain.com',
		port: 25
	}

  	process.env.MAIL_URL = 'smtp://' + encodeURIComponent(smtp.username) + ':' + encodeURIComponent(smtp.password) + '@' + encodeURIComponent(smtp.server) + ':' + smtp.port;
  	Accounts.emailTemplates.from = 'YourName <yourUsername@domain.com>';
});
```

In my case, the email server is Microsoft Exchange, and username is different from the email address. So i had to change the `Accounts.emailTemplates.from` value with my actual email address.

**Comment by tperas** [comment]
Hi @kayrules, 

Got the same problem, and after 3 days trying to make it work i still don't have any solution. 
Do you know where to find logs related to mail sending ? 
I've tried your solution but which server folder are you talking about ? 
Have you modify/delete the configuration line in the /etc/init.d/wekan file related to mail ? 

I've use the appliance to deploy Wekan on my infrastructure. 

thanks for your help.
