### ISSUE TITLE
Is there a RESTful api

### ISSUE THREAD

**Issue by xuxiangyang** [libreboard/libreboard#236]
Hi, Is there a RESTful api, so I could add a board with the script? I think it is an import feature

**Comment by xuxiangyang** [comment]
and I think, to archive a board, I need too many clicks

**Comment by ePirat** [comment]
Please do not mix topics in one bugreport, as it's else impossible to keep track of properly. If you really think that archiving a board should be easier, open a new issue for it and explain then issue a bit from your point of view. (Personally I think archiving a board isn't something I need to do so often)

**Comment by mquandalle** [comment]
Yep, I agree with the above message. Also to answer your first question we currently don't have any REST API. This is something other people are interested in as well, and there is an ongoing discussion about making one in #166.
