### ISSUE TITLE
Feature Request: Keyboard controls

### ISSUE THREAD

**Issue by dialogik** [libreboard/libreboard#241]
That would be pretty handy, stuff like 
* <kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> to navigate within the board,
* <kbd>ESC</kbd> to close current card,
* <kbd>L</kbd> to chose a label,
* <kbd>M</kbd> to manage members (assignees)

... and so on. Have a look at [Trello's keyboard shortcuts](https://trello.com/shortcuts) in order to get even more inspired.

**Comment by lebrush** [comment]
:+1:

**Comment by mquandalle** [comment]
A first set of keyboard shortcuts will be added in release v0.9 (currently in `master`).

Duplicate of #88.
