### ISSUE TITLE
Feature Request: Make hyperlinks clickable in description

### ISSUE THREAD

**Issue by dialogik** [libreboard/libreboard#243]

**Comment by dialogik** [comment]
... and in comments.

**Comment by mquandalle** [comment]
This is implemented in the upcoming v0.9 :-)

**Comment by dialogik** [comment]
Thanks for the update.

**Comment by dialogik** [comment]
Until then, a (pretty ugly) workaround does the job: Instead of the plain hyperlink

    http://www.domain.tld/path

format the link with markdown

    [http://www.domain.tld/path](http://www.domain.tld/path)
    or
    [link text](http://www.domain.tld/path)
