### ISSUE TITLE
Change Profile Avatar

### ISSUE THREAD

**Issue by yasaricli** [libreboard/libreboard#27]

**Comment by alireza-ahmadi** [comment]
I think this feature can get implemented temporarily using Gravatar, If you are OK with Gravatar I will  submit code of it in next 2 days.

**Comment by mquandalle** [comment]
I am personally fine with gravatar support, and would be happy to merge your code @alireza-ahmadi. Maybe we can use https://github.com/bengott/meteor-avatar which implement gravatar along with other features.
