### ISSUE TITLE
File attachment

### ISSUE THREAD

**Issue by kevinpk999** [libreboard/libreboard#42]
Any plans to add file/image attachment uploads ? Thanks great work so far and it's very responsive app.

**Comment by kevinpk999** [comment]
An additional feature that would be very useful is to provide a thumbnail preview on the card (main board view) if the attachment is an image.

**Comment by yasaricli** [comment]
![screen shot 2015-01-19 at 13 18 14](https://cloud.githubusercontent.com/assets/1306620/5800436/3126520c-9fe7-11e4-9ba0-436b543e7cf6.png)

![screen shot 2015-01-19 at 13 18 05](https://cloud.githubusercontent.com/assets/1306620/5800441/3f77a3ec-9fe7-11e4-83ea-8c83fdda38ae.png)

**Comment by lqtox** [comment]
I'm not sure which file store types you plan to support but I would like to recommend supporting S3  since the local server file store seems to have some issues.  When a file is uploaded, it triggers a server restart due to changes in the upload directory.

**Comment by mquandalle** [comment]
Even if it need some improvements, this is implemented in production so let's close this issue.

@lqtox We use GridFS, which is supported in all environments where we have a mongo database. If you *really* want S3 (why?!) please open a new thread and we may consider giving the option to the end-user.

**Comment by lqtox** [comment]
Agreed.  At the time the attachment feature supported only the local directory.  Using GridFS is definitely a great solution!  Thanks!

**Comment by JamborJan** [comment]
Sorry to poke this half dead issue again, only a short question: when will the sandstorm app be updated?

**Comment by mquandalle** [comment]
@JamborJan I plan to release v0.8 release-candidate on Saturday, and the final release early next week, and I'll generate a new sandstorm package for each of them.

**Comment by mquandalle** [comment]
@JamborJan The sandstorm app has been upgraded ;-)

**Comment by JamborJan** [comment]
Thanks :-)
