### ISSUE TITLE
Drag and Drop Between Lists Bug

### ISSUE THREAD

**Issue by iraycd** [libreboard/libreboard#61]
The card comes back to the original list and but it's actually changing in the background. You can see the activity is being updated in the below video.

http://www.youtube.com/watch?v=Xwm0nAOvNqc

I didn't really understand the drag and drop event in Metrello. Can you explain that.

**Comment by yasaricli** [comment]
@mquandalle ?

https://github.com/yasaricli/metrello/commit/5fb35d15becc13f0cc4a1dde167bae0a4fa75d02#diff-f6aecbdd5dbe8a2f6e17236f492e4a48L20

**Comment by mquandalle** [comment]
Not sure what the problem, but it seems to be fixed on master.

@iraycd I'll ping you when this is deployed so you can verify if the issue is effectively fixed.

**Comment by iraycd** [comment]
:+1: Done.

**Comment by mquandalle** [comment]
I'm seeing this bug again in production

**Comment by mquandalle** [comment]
Related: https://github.com/jquery/jquery-ui/pull/1253
