### ISSUE TITLE
Popups should be hidden on a click away

### ISSUE THREAD

**Issue by Slava** [libreboard/libreboard#62]
Click on any button that opens a popup or a submit form such as `#AddCardForm`. A popup/form opens. Click on any part of the body, that is not a button. The popup/form is expected to be closed.

A simple dumb solution that I came up with is listening on the `blur` event, but it is bad, because clicking on buttons is also triggering a blur event.

**Comment by mquandalle** [comment]
Yes, the popup system needs to be improved. I plan to make a general object that we can use more easily in the code (there is a lot of duplicate code regarding click management for instance). And there is also #54.

**Comment by mquandalle** [comment]
About the implementation we can simply add a event listener on the `body` that will close the popup. Then we add a click event on the popup and stop its propagation so that the event does not bubble up to the `body` tag.
