### ISSUE TITLE
Better accounts

### ISSUE THREAD

**Issue by mquandalle** [libreboard/libreboard#66]
Currently users can only sign up using a pseudonym, an email, and a password; and the email address is not verified. I think we should configure github and facebook authentication. We also need to provide the form for those who have forgotten their passwords and want to re-generate it.

All of these features are particularly easy to implement in meteor, we just need to figure out which packages we want to use and what UI we want. We probably don't need to follow Trello here.

**Comment by orges** [comment]
Totally agree

**Comment by Shekar73** [comment]
How about this login screen...kind of functional keeping in character of the app....

![image](https://cloud.githubusercontent.com/assets/203255/5787210/8842a0c4-9dab-11e4-973b-4c43e8f69e80.png)

**Comment by Shekar73** [comment]
BTW, thanks for all the comments in the app :+1: immensely helpful in my learning meteor using the app

**Comment by neandrake** [comment]
Should LDAP authentication be included within the scope of this issue?

**Comment by mquandalle** [comment]
@neandrake I think it's better to open a separate issue of LDAP integration.

**Comment by andreioprisan** [comment]
I think Google Apps integration would be a better bet and you can use this in the future feature development (i.e. managed team access)

**Comment by ocdtrekkie** [comment]
Doesn't Google Apps for login defeat a lot of the point of self-hosting?

**Comment by andreioprisan** [comment]
@ocdtrekkie of course not, they're different concepts. This isn't for data hosting linked to a Google account, this is only for login. Twitter login doesn't give you email address so you can't use it for email notifications. Facebook login does give you email address but in any semi-professional setting, you will not want to link your Facebook profile. Again, this is only for the Google Apps login and potential expansion to sign up other users within an organization to create user accounts, down the line. 
This wouldn't take away from the current email signup that's not linked to any service, nor should it.

**Comment by miketweaver** [comment]
There should also be a way to limit signups. In a corporate environment I don't want random users signing up and using my server, only those that are given access.

**Comment by Shekar73** [comment]
I agree with @miketweaver :+1: . Also, it also important that from a privacy and data protection point of view I want to limit the searching and signups  that admin has provided access

**Comment by mquandalle** [comment]
This is fixed in the `new-ui` branch.
