### ISSUE TITLE
Change Background color.

### ISSUE THREAD

**Issue by yasaricli** [libreboard/libreboard#67]

**Comment by jamesa** [comment]
Are you looking for a new color palette to change the whole project to? Or like Trello has where you can select your own background color on a per-board basis?

**Comment by mquandalle** [comment]
This issue is about implementing the per board background color, @yasaricli plan to work on this on Sunday (it's possible that I'll do it tomorrow). Personally I'm also interested in a new palette to distinguish visually from Trello. Maybe http://flatuicolors.com?
