### ISSUE TITLE
Creating board with multibyte character failed

### ISSUE THREAD

**Issue by ryuzee** [libreboard/libreboard#70]
When I created boards that name contains multibyte characters such as "謝謝" and "감사합니다", I was redirected to 404 page. After back to "My Boards", there were the boards I created but these are not accessible.

**Comment by mquandalle** [comment]
Probably a bug with https://github.com/yasaricli/meteor-slugify

**Comment by mquandalle** [comment]
This is fixed on master and on http://libreboard.com. Thank you for the bug report and for [your article](http://www.ryuzee.com/contents/blog/7032) :-)

Would you be interested in translating the application in Japanese ?

**Comment by ryuzee** [comment]
@mquandalle I've confirmed it works fine with mltibyte characters in board name. Thank you very much for handling the issue. I am willing to send a PR including Japanese translation :-)

**Comment by mquandalle** [comment]
Oh, if you want to participate in the translatin please use https://www.transifex.com/organization/libreboard/dashboard/libreboard. That would be easier for us to manage than individual PRs.

**Comment by ryuzee** [comment]
@mquandalle Understood. I've just started translation on the platform you indicated. thanks for the guidance.
