### ISSUE TITLE
Redirect Metrello website to Libreboard

### ISSUE THREAD

**Issue by Slava** [libreboard/libreboard#77]
Right now nothing on Metrello.meteor.com indicates that the project has moved.

**Comment by mquandalle** [comment]
I don't have deploy privilege on metrello.meteor.com, @yasaricli could you please deploy a new meteor application containing a single file the following code:

```
if (Meteor.isServer) {
  WebApp.connectHandlers.use(function(req, res, next) {
    res.writeHead(301, { 'Location': 'http://libreboard.com' });
    res.end();
  });
}
```

**Comment by mquandalle** [comment]
Thank you very much @yasaricli
