### ISSUE TITLE
TypeError: Meteor.update is not a function

### ISSUE THREAD

**Issue by ktosiek** [libreboard/libreboard#79]
I've just registered on libreboard.com.
I'm getting "TypeError: Meteor.update is not a function" when moving a card between lists, but I could add that card. This is on Firefox 34.0.5 (on NixOS).

This is the complete console output for refreshing a page and trying to move a card:

    The connection to wss://ddp--9786--54ac5610072cd34a440115f6.meteor.com/sockjs/148/hd6ify3f/websocket was interrupted while the page was loading. 0f606dd0e8ac71bf8c8276045baf1d17a2b7ad12.js:34
    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ddp--7509--54ac5610072cd34a440115f6.meteor.com/sockjs/info?cb=gju1yxo6ap. This can be fixed by moving the resource to the same domain or enabling CORS. info
    mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create 0f606dd0e8ac71bf8c8276045baf1d17a2b7ad12.js:120
    GET http://www.gravatar.com/avatar/37c96ceb704f2cd5093e73187067b6d1 [HTTP/1.1 404 Not Found 196ms]
    TypeError: Meteor.update is not a function

**Comment by mquandalle** [comment]
Sorry for that, we are moving fast and breaking things... This should is fixed now (and deployed).
