### ISSUE TITLE
Issue with adding and editing with the filtered cards

### ISSUE THREAD

**Issue by Shekar73** [libreboard/libreboard#80]
When Filter is on cannot add any new cards  or edit existing cards in the filtered result set....

**Comment by mquandalle** [comment]
I'm not sure what would be the expected user experience here? If you filter on the blue label, and add a new card without this blue label, do you expect it do be visible in the filtered view? Or maybe we can just disable the “add a new card” link?

**Comment by Shekar73** [comment]
My 2 cents would be  disabling the 'add a new card' , unless the team  thinks otherwise. My reasoning behind is, if as a user I see the link to add new card on the filtered result set and when I click that option with nothing happening on the form, then it might create bad experience.

**Comment by mquandalle** [comment]
I agree with you, but in another way the user will also be confused if he tries to add a card and the “add a card…” link has disappeared. So we need to write something like “Disable filtering to add new cards”.

Or we can just follow what Trello does and not filter newly created cards.

**Comment by Shekar73** [comment]
That is true as well, having his familiar options would help smoother experience flow rather being 'stuck' and think about 'exit' options when he is on the filtered view. My vote goes for following Trello and not filter newly created cards,  as it has been already been tested in the real world  from the user experience  pov...
