### ISSUE TITLE
Removing member from inside the card is failing

### ISSUE THREAD

**Issue by Shekar73** [libreboard/libreboard#82]
Clicking on the member inside the card  and selecting the option to remove from this card is not working

**Comment by mquandalle** [comment]
I cannot reproduce this issue, maybe it is a similar story as #81?

**Comment by Shekar73** [comment]
hmmm that is weird. On my side, this is the issue on my local instance and on libreboard.com. Here are the screenshots of my flow...

Below is the member assignment of couple of cards

![image](https://cloud.githubusercontent.com/assets/203255/5793498/669d41ea-9efa-11e4-93fd-2c52064cf0d1.png)

 I click on the member name inside the card to select remove the member from card..

![image](https://cloud.githubusercontent.com/assets/203255/5793509/08906d74-9efb-11e4-8e2d-d1247c8709e0.png)

 But I still see the member even after I clicked on the remove option..

![image](https://cloud.githubusercontent.com/assets/203255/5793520/72ac027c-9efb-11e4-9d6a-b4d4f5c93fae.png)


This is the same issue on my local branch as well....sorry I don't have a pull request to submit at this point

**Comment by mquandalle** [comment]
Oh ok, I tested the wrong functionality (removing a member by the action button on the detailled view). Tagging this as a bug.

**Comment by mquandalle** [comment]
I think I have found the issue: https://github.com/libreboard/libreboard/blob/13dc98266535a1b4fa339dcbc55ecbf486395f22/client/views/cards/events.js#L65  ^^

**Comment by Shekar73** [comment]
stuff happens.... :+1:
