### ISSUE TITLE
Increase the card drop area on empty lists

### ISSUE THREAD

**Issue by Kaligule** [libreboard/libreboard#83]
When I click on "add a card.." in the empty list everxthing works. I assume this creates a card of temporarly existence.

**Comment by mquandalle** [comment]
I cannot reproduce this bug. Could you provide more details?

**Comment by Kaligule** [comment]
Hmmm, It seems the mistake was on my side. I tried to drag the card on the "add a card" button, not on the list headline. This doesn't work in Libreboard (it does in Trello).
So this is not really a bug. Sorry.

**Comment by mquandalle** [comment]
I imagine we can improve the user experience here.

**Comment by mquandalle** [comment]
Fixed in 6db01bb3c7bbcf3e5451dd828d3d0932eb5efec3.
