### ISSUE TITLE
Hover/drop area a bit wonky

### ISSUE THREAD

**Issue by Squ34k3rZ** [libreboard/libreboard#85]
AMAZING work! Good job, guys!

When you click and drag a box to a list, if you're hovering over the 'Add Card' section, it won't create the hover effect. If the list is empty, for example, you have to hover over the title to get the card in there. This can be a bit wonky feeling. I'd create a pull request myself, but something tells me this is a 15 minute fix for the guy who knows where the hover effect is firing in the code. Please make sure the hover effect happens over the entire list div. Thanks!

**Comment by mquandalle** [comment]
I will implement this along with the new UI. But it's certainly not a “15 minutes fix” ;-)
