### ISSUE TITLE
Can't access libreboard roadmap

### ISSUE THREAD

**Issue by TheSneakyNarwhal** [libreboard/libreboard#86]
I can't access the [board posted on the readme](http://libreboard.com/boards/MeSsFJaSqeuo9M6bs/libreboard-roadmap) whether I'm logged in or not. The page below will always show up. After selecting "logging in", it redirects me to my boards.

![capture](https://cloud.githubusercontent.com/assets/5177280/5812555/495e26e8-a022-11e4-80f0-17e65f34b645.PNG)

Maybe the board just doesn't exist or isn't set as public?

**Comment by yasaricli** [comment]
Thank you very much.
