### ISSUE TITLE
[UX] Empty text = delete please :)

### ISSUE THREAD

**Issue by Squ34k3rZ** [libreboard/libreboard#87]
Hey guys, UX nerd here. Here's what I noticed about my actual behavior when using your product:

When I wanted to delete something, the first thing I did was delete all the text in a box/list. Then I hit enter and nothing happened. (No feedback. At the very least, if you guys have time for this nice-to-have feature, an info box with the error message would be helpful. Then when the person starts typing again it goes away). Then I tried hitting save and again, nothing happened. No error message either.

I say if people want to delete their boxes and lists by deleting all the text inside them, let them do it!

if ( $(#div).val.length === 0) {
$delete $(#div);
}

Something like that. Thanks guys!

**Comment by mquandalle** [comment]
I don't think this is a behavior we want to encourage. If you want to delete a card you have to explicitly click on a “delete” button somewhere in the UI. Do you think it would be a good idea if file systems implemented a “rename this file to blank to delete its content”. How do you retrieve the original name if you have done this by mistake?

What I plan to implement is a “drag here to archive” when you are dragging a card. I think that would solve this issue in a better way.
