### ISSUE TITLE
[UX] Add keyboard shortcuts

### ISSUE THREAD

**Issue by florentdestremau** [libreboard/libreboard#88]
One thing i love about Trello is the very large panel of keyboard shortcuts allowing me to do close to anything. A support of this would be greatly appreciated ! :)

**Comment by fnkr** [comment]
+1

**Comment by mquandalle** [comment]
This is implemented in the current master branch and will be shipped in v0.9 release.

**Comment by florentdestremau** [comment]
:+1:
