### ISSUE TITLE
UI bug when moving cards between lists

### ISSUE THREAD

**Issue by Bersam** [libreboard/libreboard#93]
I was working with libreboard.com and suddenly this happened.

![libreboard-bug](https://cloud.githubusercontent.com/assets/497148/5819055/02ec64f0-a0d0-11e4-8e6b-ddacf1c5677a.png)

**Comment by ojosdegris** [comment]
There is another bug, when moving ticket 1 from list A to list B , log message will say
   
    User moved A from B to undefined.

instead of saying

    User moved 1 from A to B

**Comment by mquandalle** [comment]
@ojosdegris This bug was fixed in 0.8; thanks (next time, please open a separate github issue, it makes things easier to manage)

@Bersam I reproduced this bug and will work on a fix along with the new UI for the next release

**Comment by mquandalle** [comment]
Fixed on the `new-ui` branch
