### ISSUE TITLE
Design Review

### ISSUE THREAD

**Issue by Squ34k3rZ** [libreboard/libreboard#97]
Hey guys, I'm a UX nerd who's more focused on content/simplicity than pretty illustrations/style. With that said, I'm going to include some design principles to improve the overall "look"

Structure (Info Architecture)
Instead of a boards button, a side navigation seems more fitting.

The good:
You guys picked locations that follow conventions, which is very good. I know you're mimicking Trello but I still think you did an excellent job. Just wiring this together is very impressive!

Users is in the right place (where "utilities" go in the top right)
Activity seems alright

Just spittballing here:
The plus sign is ambiguous. I had to hover over it to understand what it meant. Based on my actual behavior using this page, I think it'd benefit from a label. So maybe you guys could include your plus icon with a label saying "Create Board"? And instead of putting it up top and to the right, you could have it in next to the "Boards" button.

I would make clicking on "Libreboard" in the top center bring you back to the "Boards" page
I'd probably actually delete the boards page and make that a secondary vertical nav.

You guys can simplify your UI. Right now there's no indication that you can re-name the title. I clicked on it to rename it, and see you already built in the functionality! So maybe you guys could put a gear icon and a label that says "Settings" or "Edit" (Idk the /right/ label for this one) next to the Welcome Board title? And then you can clean up the UI a bit: put the star, a button or input box to re-name it, and the privacy lock inside the Settings modal. That simplifies your UI even more!

**Comment by Squ34k3rZ** [comment]
As for how to make things look "good"... it's all about contrast. So if you have bigger text on the list titles with regular sized text in the boxes, it's going to look better. When someone says if something looks good, they probably mean there's a lot of contrast. You already have some of that going on with the dark background and light lists. Big + small. Dark + light. This is how you make contrast.

**Comment by ozodrukh** [comment]
i'm not ui/ux designer, but i draw simple sketch in material like style, please criticize it we need do something comfortable to use
![screen shot 2015-01-23 at 12 16 22 am](https://cloud.githubusercontent.com/assets/3184950/5862618/1f06bd2c-a295-11e4-9423-feb4cd117f88.png)

**Comment by ocdtrekkie** [comment]
I will cry many tears if this goes material design. Many. Tears. #materialnono

**Comment by ozodrukh** [comment]
@ocdtrekkie , what u hate material design? i thought i draw beautiful implementation :smile:

**Comment by mquandalle** [comment]
Let's move this conversation into #94.

**Comment by ocdtrekkie** [comment]
@ozodrukh Your mock-up is fine, but I don't think a free software project should be implementing Google's branding. And material design has poor contrast between various layers.
